name: Build App

on:
    push:
        branches:
            - tests
    pull_request:
        branches:
            - tests

jobs:
    test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./sleep_tracker_app
        steps:
            - uses: actions/checkout@v4
            - uses: subosito/flutter-action@v2
              with:
                channel: stable
                flutter-version: 3.22.2

            - run: flutter pub get

            - run: flutter test test/unit_test.dart

            - run: flutter analyze lib/main.dart